apiVersion: v1
kind: Service
metadata:
  name: process-ui-svc
  namespace: process-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 32500
  selector:
    app: process-ui
